### ISSUE TITLE
Syntax Error when installing

### ISSUE THREAD

**Issue by chrisgrieser** [yoursamlan/pubsidian#2] opened 2021-08-22 15:25 UTC
Hi, thanks for sharing this!

So, I tried to follow your setup instructions and when to I ran `python convert2web.py`, it gave me the following error

```
File "convert2web.py", line 60
SyntaxError: Non-ASCII character '\xc3' in file convert2web.py on line 60, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

I tried searching through the python script and search for `\xn3` but it didn't find any occurence?

**Comment by yoursamlan** [comment] 2021-08-22 17:03
Hi. Thank you for using pubsidian.

As mentioned [here,](https://stackoverflow.com/questions/26899235/python-nltk-syntaxerror-non-ascii-character-xc3-in-file-sentiment-analysis) I think just putting  ```# coding=utf-8```  on the top of ```convert2web.py``` can resolve this issue.

I've updated the script. You can either manually download and run the script again, or simply add the aforementioned line at the top of convert2web.py to resolve the issue.

Please let me know if the issue is fixed. 

Since 24 hr has passed without any comment, I'm assuming the problem is fixed and thus closing this thread. Feel free to raise an issue again if you face any problem. Thank you.

**Closed as completed** 2021-08-24 06:45 UTC
