### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by EhuddR** [yoursamlan/pubsidian#3] opened 2021-09-18 17:14 UTC
Hi! First of all your work is pretty amazing. I've been looking for an option like this since I meet obsidian last year. I would like to ask if it's possible to have linux support? Because as is the app only works on Windows.

Best regards.

**Comment by yoursamlan** [comment] 2021-09-19 04:51
Hi, Thank you so much.
Currently, there is no stand-alone application for Linux; but you can run the [**native python script**](https://github.com/yoursamlan/pubsidian/tree/main/tools/GUI), to generate a website from your obsidian notes --

- STEP-1: CONVERSION:
    -  **Make sure, you have installed Python 3.5 or later.**
    -  Now, **fork and download** [yoursamlan/pubsidian](https://github.com/yoursamlan/pubsidian) to your local machine.
    -  After downloading the repository, go to the ```tools/GUI``` directory.
    - Copy and paste all the files (including ```./web```) of the ```GUI``` directory to the folder of your obsidian notes [i.e where your notes (.md) are stored].
    -  Now open the terminal there and run
        ``` pip install requirements.txt ```
    -  Now open the command prompt again and run
    ``` python PubsidianConverter.py```
    -  You will see a window, something like this:
    - <img src="https://user-images.githubusercontent.com/33586885/130856672-35454bcd-3386-4afb-8ba7-33cba5b96d1d.png" width="50%">
    -  Enter your name (It will be reflected as ```***'S NOTEBOOK``` in your pubsidian website) and hit ```Convert to Pubsidian```. Now, a pop-up window will arrive. Select the ```Attachment folder, i.e., where the images, used inside your obsidian notes are stored``` from the pop-up window.
    - After running successfully, you'll get an ```OUTPUT``` directory, containing three elements: ```index.html```,```data.json``` and ```pages``` directory.

- STEP-2: HOSTING:
    -  Drag and drop your ```OUTPUT``` directory in [netlify]("https://app.netlify.com/drop")

Voila!! 🥳🥳 your site is online.

Reply in this thread, if you face any problems while converting the notes. 

Thank you.

**Comment by yoursamlan** [comment] 2021-09-22 05:42
Since it's 48 hrs from the last reply, I'm assuming, the issue is fixed and thus closing this thread. If you have any queries/ suggestions in the future, please feel free to raise another issue. Thank you.

**Closed as completed by yoursamlan** 2021-09-22 05:42 UTC

**Comment by EhuddR** [comment] 2021-09-24 21:40
I'm sorry for not responding at time I have a lot in my hands right now. 
Thanks for your help and for this amazing tool it works as expected.

**Comment by yoursamlan** [comment] 2021-09-27 04:13
Thank you so much. Glad you liked it. Feel free to contact me for any bugs/suggestions to improve the program :)

**Comment by PabloLION** [comment] 2021-11-24 02:32
Hi @yoursamlan. I just tested this on Mac with M1 and I like your project! Can you link this issue to the main README? It took me a while to get here. (I reckon obsidian publish is overcharging and Idk why I sponsored them)
